name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # ၁။ Docker Buildx ကို တပ်ဆင်ခြင်း (Advanced caching အတွက် လိုအပ်ပါတယ်)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ၂။ Docker Hub သို့ Login ဝင်ခြင်း
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # ၃။ Docker Image တည်ဆောက်ပြီး Docker Hub ဆီ တင်ခြင်း (Caching စနစ်ပါဝင်သည်)
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./next-js-app
        file: ./next-js-app/Dockerfile
        push: true
        tags: mayyadanarmaung/next-js-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
